name: Build and test
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            goarch: amd64
          - os: ubuntu-latest
            goarch: arm64
          - os: windows-latest
            goarch: amd64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24'
      - name: Run tests
        run: go test -count=1 -timeout 300s ./...

  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24'
      - name: Run benchmarks
        run: go test ./internal/multiplex/ -bench=BenchmarkObfs -bench=BenchmarkDeobfs -benchtime=1s -count=1
